/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Ajie
 */
public class GUIPesan extends javax.swing.JFrame {

    /**
     * Creates new form GUIPesan
     */
    public GUIPesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbHeadPesan = new javax.swing.JLabel();
        bPesanTiket = new javax.swing.JButton();
        bCancelTiket = new javax.swing.JButton();
        paneBiodata = new javax.swing.JPanel();
        tNoHP = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        lbNama = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        tUsia = new javax.swing.JTextField();
        lbUsia = new javax.swing.JLabel();
        tNoKTP = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        lbNoHp = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNoKTP = new javax.swing.JLabel();
        lbBioPesan = new javax.swing.JLabel();
        paneTiket = new javax.swing.JPanel();
        lbHasTujuan = new javax.swing.JLabel();
        lbDari = new javax.swing.JLabel();
        lbJam = new javax.swing.JLabel();
        lbHasJam = new javax.swing.JLabel();
        lbTgl = new javax.swing.JLabel();
        lbHasTgl = new javax.swing.JLabel();
        lbAnak2 = new javax.swing.JLabel();
        lbPesawat = new javax.swing.JLabel();
        lbTiket = new javax.swing.JLabel();
        tDewasa = new javax.swing.JTextField();
        lbDewasa = new javax.swing.JLabel();
        lbBayi = new javax.swing.JLabel();
        tBayi = new javax.swing.JTextField();
        lbTujuan = new javax.swing.JLabel();
        lbHasDari = new javax.swing.JLabel();
        lbHasPswt = new javax.swing.JLabel();
        tAnak2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbHeadPesan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHeadPesan.setText("PESAN TIKET PESAWAT SEGERA!!");

        bPesanTiket.setText("Pesan Tiket");

        bCancelTiket.setText("Cancel");

        paneBiodata.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNama.setText("Nama Lengkap");

        lbUsia.setText("Usia");

        lbNoHp.setText("No. HP");

        lbAlamat.setText("Alamat");

        lbNoKTP.setText("Nomor KTP");

        lbBioPesan.setText("BIODATA PEMESAN");

        javax.swing.GroupLayout paneBiodataLayout = new javax.swing.GroupLayout(paneBiodata);
        paneBiodata.setLayout(paneBiodataLayout);
        paneBiodataLayout.setHorizontalGroup(
            paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
            .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBiodataLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbBioPesan)
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addComponent(lbNama)
                            .addGap(39, 39, 39)
                            .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbUsia)
                                .addComponent(lbAlamat)
                                .addComponent(lbNoHp)
                                .addComponent(lbNoKTP))
                            .addGap(57, 57, 57)
                            .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tNoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tUsia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        paneBiodataLayout.setVerticalGroup(
            paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBiodataLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbBioPesan)
                    .addGap(6, 6, 6)
                    .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lbNama)))
                    .addGap(6, 6, 6)
                    .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lbNoKTP))
                        .addComponent(tNoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lbUsia)
                            .addGap(12, 12, 12)
                            .addComponent(lbAlamat))
                        .addGroup(paneBiodataLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(tUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(paneBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNoHp))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        paneTiket.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbHasTujuan.setText("-------");

        lbDari.setText("Dari");

        lbJam.setText("Jam");

        lbHasJam.setText("------");

        lbTgl.setText("Tanggal");

        lbHasTgl.setText("------");

        lbAnak2.setText("Anak-anak");

        lbPesawat.setText("Pesawat");

        lbTiket.setText("TICKET");

        lbDewasa.setText("Dewasa");

        lbBayi.setText("Bayi");

        lbTujuan.setText("Tujuan");

        lbHasDari.setText("-------");

        lbHasPswt.setText("------");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ID transaksi anda");

        javax.swing.GroupLayout paneTiketLayout = new javax.swing.GroupLayout(paneTiket);
        paneTiket.setLayout(paneTiketLayout);
        paneTiketLayout.setHorizontalGroup(
            paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addComponent(lbDewasa)
                        .addGap(6, 6, 6)
                        .addComponent(tDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lbAnak2)
                        .addGap(4, 4, 4)
                        .addComponent(tAnak2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbBayi)
                        .addGap(4, 4, 4)
                        .addComponent(tBayi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addComponent(lbDari)
                        .addGap(108, 108, 108)
                        .addComponent(lbTujuan)
                        .addGap(7, 7, 7)
                        .addComponent(lbHasTujuan))
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTgl)
                            .addComponent(lbPesawat))
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneTiketLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbHasPswt))
                            .addGroup(paneTiketLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHasDari)
                                    .addGroup(paneTiketLayout.createSequentialGroup()
                                        .addComponent(lbHasTgl)
                                        .addGap(55, 55, 55)
                                        .addComponent(lbJam)
                                        .addGap(21, 21, 21)
                                        .addComponent(lbHasJam))))))
                    .addComponent(lbTiket)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTiketLayout.setVerticalGroup(
            paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTiketLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAnak2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDewasa)
                            .addComponent(lbAnak2)
                            .addComponent(lbBayi))))
                .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDari)
                            .addComponent(lbHasDari)))
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbTujuan))
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbHasTujuan)))
                .addGap(6, 6, 6)
                .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJam)
                    .addComponent(lbHasJam)
                    .addGroup(paneTiketLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTgl)
                            .addComponent(lbHasTgl))
                        .addGap(6, 6, 6)
                        .addGroup(paneTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHasPswt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbHeadPesan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(paneBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paneTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPesanTiket)
                .addGap(79, 79, 79)
                .addComponent(bCancelTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbHeadPesan)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneBiodata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPesanTiket)
                    .addComponent(bCancelTiket))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPesan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton bCancelTiket;
    private javax.swing.JButton bPesanTiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbAnak2;
    private javax.swing.JLabel lbBayi;
    private javax.swing.JLabel lbBioPesan;
    private javax.swing.JLabel lbDari;
    private javax.swing.JLabel lbDewasa;
    private javax.swing.JLabel lbHasDari;
    private javax.swing.JLabel lbHasJam;
    private javax.swing.JLabel lbHasPswt;
    private javax.swing.JLabel lbHasTgl;
    private javax.swing.JLabel lbHasTujuan;
    private javax.swing.JLabel lbHeadPesan;
    private javax.swing.JLabel lbJam;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNoHp;
    private javax.swing.JLabel lbNoKTP;
    private javax.swing.JLabel lbPesawat;
    private javax.swing.JLabel lbTgl;
    private javax.swing.JLabel lbTiket;
    private javax.swing.JLabel lbTujuan;
    private javax.swing.JLabel lbUsia;
    private javax.swing.JPanel paneBiodata;
    private javax.swing.JPanel paneTiket;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tAnak2;
    private javax.swing.JTextField tBayi;
    private javax.swing.JTextField tDewasa;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNoHP;
    private javax.swing.JTextField tNoKTP;
    private javax.swing.JTextField tUsia;
    // End of variables declaration                   
    
    public JLabel getLbDari(){
        return this.lbHasDari;
    }
    
    public JLabel getLbTujuan(){
        return this.lbHasTujuan;
    }
    
    public JLabel getLbPesawat(){
        return this.lbHasPswt;
    }
    
    public JLabel getLbJam(){
        return this.lbHasJam;
    }
    
    public JLabel getLbbook(){
        return this.jLabel1;
    }
    
    public JLabel getLbTanggal(){
        return this.lbHasTgl;
    }
    
    public JButton getBPesan(){
        return this.bPesanTiket;
    }
    
    public JTextField getTNama(){
        return this.tNama;
    }
    
    public JTextField getTUsia(){
        return this.tUsia;
    }
    
    public JTextField getTAlamat(){
        return this.tAlamat;
    }
    
    public JTextField getTNoKTP(){
        return this.tNoKTP;
    }
    
    public JTextField getTNoHP(){
        return this.tNoHP;
    }
    
    public JTextField getTDws(){
        return this.tDewasa;
    }
    
    public JTextField getTBayi(){
        return this.tBayi;
    }
    
    public JTextField getTAnak2(){
        return this.tAnak2;
    }
    
    public void addListener(ActionListener e){
        getBPesan().addActionListener(e);
    }
}
