/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author Ajie
 */
public class GUIReservation extends javax.swing.JFrame{
    
    /**
     * Creates new form GUIReservation
     */
    public GUIReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        paneSearchTicket = new javax.swing.JPanel();
        pSearchTicket = new javax.swing.JPanel();
        lblDari = new javax.swing.JLabel();
        lbKe = new javax.swing.JLabel();
        cbDari = new javax.swing.JComboBox();
        btSearch = new javax.swing.JButton();
        cbTanggal = new javax.swing.JComboBox();
        lbTanggal = new javax.swing.JLabel();
        cbKe = new javax.swing.JComboBox();
        spTicket = new javax.swing.JScrollPane();
        tTicket = new javax.swing.JTable();
        paneButton = new javax.swing.JPanel();
        bPesan = new javax.swing.JButton();
        bBayar = new javax.swing.JButton();
        paneHeader = new javax.swing.JPanel();
        lbJudul = new javax.swing.JLabel();
        lbAkun = new javax.swing.JLabel();
        MenuReservation = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuFileLogin = new javax.swing.JMenuItem();
        MenuFileLogout = new javax.swing.JMenuItem();
        MenuFileExit = new javax.swing.JMenuItem();
        MenuKelola = new javax.swing.JMenu();
        MenuKelolaPegawai = new javax.swing.JMenuItem();
        MenuKelolaCustomer = new javax.swing.JMenuItem();
        MenuKelolaJadwal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pSearchTicket.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDari.setText("Dari");

        lbKe.setText("Ke");

        btSearch.setText("Search");

        lbTanggal.setText("Tanggal");

        cbKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSearchTicketLayout = new javax.swing.GroupLayout(pSearchTicket);
        pSearchTicket.setLayout(pSearchTicketLayout);
        pSearchTicketLayout.setHorizontalGroup(
            pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDari)
                    .addComponent(lbTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSearchTicketLayout.createSequentialGroup()
                        .addComponent(cbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSearchTicketLayout.createSequentialGroup()
                        .addComponent(cbDari, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbKe)
                        .addGroup(pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pSearchTicketLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btSearch))
                            .addGroup(pSearchTicketLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbKe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pSearchTicketLayout.setVerticalGroup(
            pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTanggal))
                .addGap(9, 9, 9)
                .addGroup(pSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDari)
                    .addComponent(lbKe)
                    .addComponent(cbDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pesawat", "Tanggal", "Jam", "Harga", "Harga anak-anak", "idTicket"
            }
        ));
        spTicket.setViewportView(tTicket);

        paneButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bPesan.setText("Pesan Ticket");

        bBayar.setText("Bayar Ticket");

        javax.swing.GroupLayout paneButtonLayout = new javax.swing.GroupLayout(paneButton);
        paneButton.setLayout(paneButtonLayout);
        paneButtonLayout.setHorizontalGroup(
            paneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneButtonLayout.setVerticalGroup(
            paneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBayar)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneSearchTicketLayout = new javax.swing.GroupLayout(paneSearchTicket);
        paneSearchTicket.setLayout(paneSearchTicketLayout);
        paneSearchTicketLayout.setHorizontalGroup(
            paneSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchTicketLayout.createSequentialGroup()
                .addComponent(pSearchTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(spTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        paneSearchTicketLayout.setVerticalGroup(
            paneSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSearchTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pSearchTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        getContentPane().add(paneSearchTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        paneHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbJudul.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbJudul.setText("PLANE TICKET RESERVATION");

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneHeaderLayout.createSequentialGroup()
                    .addGap(0, 124, Short.MAX_VALUE)
                    .addComponent(lbJudul)
                    .addGap(0, 125, Short.MAX_VALUE)))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneHeaderLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(lbJudul)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        getContentPane().add(paneHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 30));

        lbAkun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lbAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 90, 20));

        MenuFile.setText("File");

        MenuFileLogin.setText("Login");
        MenuFile.add(MenuFileLogin);

        MenuFileLogout.setText("Logout");
        MenuFile.add(MenuFileLogout);

        MenuFileExit.setText("Exit");
        MenuFile.add(MenuFileExit);

        MenuReservation.add(MenuFile);

        MenuKelola.setText("Kelola");

        MenuKelolaPegawai.setText("Pegawai");
        MenuKelola.add(MenuKelolaPegawai);

        MenuKelolaCustomer.setText("Customer");
        MenuKelola.add(MenuKelolaCustomer);

        MenuKelolaJadwal.setText("Jadwal");
        MenuKelola.add(MenuKelolaJadwal);

        MenuReservation.add(MenuKelola);

        setJMenuBar(MenuReservation);

        pack();
    }// </editor-fold>                        

    private void cbKeActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIReservation().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify                     
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuFileExit;
    private javax.swing.JMenuItem MenuFileLogin;
    private javax.swing.JMenuItem MenuFileLogout;
    private javax.swing.JMenu MenuKelola;
    private javax.swing.JMenuItem MenuKelolaCustomer;
    private javax.swing.JMenuItem MenuKelolaJadwal;
    private javax.swing.JMenuItem MenuKelolaPegawai;
    private javax.swing.JMenuBar MenuReservation;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bPesan;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSearch1;
    private javax.swing.JComboBox cbDari;
    private javax.swing.JComboBox cbDari1;
    private javax.swing.JComboBox cbKe;
    private javax.swing.JComboBox cbTanggal;
    private javax.swing.JComboBox cbTanggal1;
    private javax.swing.JLabel lbAkun;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbKe;
    private javax.swing.JLabel lbKe1;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lbTanggal1;
    private javax.swing.JLabel lblDari;
    private javax.swing.JLabel lblDari1;
    private javax.swing.JPanel pSearchTicket;
    private javax.swing.JPanel pSearchTicket1;
    private javax.swing.JPanel paneButton;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneSearchTicket;
    private javax.swing.JScrollPane spTicket;
    private javax.swing.JTable tTicket;
    // End of variables declaration                   

    public JButton getbtSearch(){
        return this.btSearch;
    }
    
    public JButton getbPesan(){
        return this.bPesan;
    }
    
    public JButton getbBayar(){
        return this.bBayar;
    }
    
    public JMenuItem getMenuFile(){
        return this.MenuFile;
    }
    
    public JMenuItem getMenuKelola(){
        return this.MenuKelola;
    }
    
    public JMenuItem getMenuFileExit(){
        return this.MenuFileExit;
    }
    
    public JMenuItem getMenuFileLogin(){
        return this.MenuFileLogin;
    }
    
    public JMenuItem getMenuFileLogout(){
        return this.MenuFileLogout;
    }
    
    public JLabel getlbAkun(){
        return this.lbAkun;
    }
    
    public JComboBox getCbTanggal(){
        return this.cbTanggal;
    }
    
    public JComboBox getCbdari(){
        return this.cbDari;
    }
    
    public JComboBox getCbKe(){
        return this.cbKe;
    }
     
    public JTable getTTicket(){
        return this.tTicket;
    }
       
    public void addListener(ActionListener e){
        getbtSearch().addActionListener(e);
        getbBayar().addActionListener(e);
        getbPesan().addActionListener(e);
        getMenuFileExit().addActionListener(e);
        getMenuFileLogin().addActionListener(e);
        getMenuFileLogout().addActionListener(e);
    }
}
